import Head from 'next/head'
import Image from 'next/image'
import { Box, Typography, Divider} from '@mui/material';

export default function Layout({children}) {
  
  return (
    <div >
      <Head>
        <title>Guessing Game</title>
        <meta name="Guessing Game Java & next.js" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box sx={{ width: '100%', textAlign: 'center', padding: '2rem' }}>
          {children}
        </Box>
      </main>

    </div>
  )
}
